package jdb

const (
	MSG_KIND_NOT_DEFINED         = "Kind not defined"
	MSG_INVALID_NAME             = "Invalid name (%s)"
	MSG_JDB_NOT_DEFINED          = "JDB not defined"
	MSG_DRIVER_NOT_FOUND         = "Driver not found (%s)"
	MSG_DATABASE_NOT_DEFINED     = "Database not defined"
	MSG_DRIVER_NOT_DEFINED       = "Driver not defined"
	MSS_PARAM_REQUIRED           = "Parámetro requerido (%s)"
	MSG_DATABASE_NOT_FOUND       = "Database not found (%s)"
	MSG_DATABASE_IS_REQUIRED     = "Database is required"
	MSG_SCHEMA_NOT_FOUND         = "Schema not found (%s)"
	MSG_QUERY_FAILED             = "Query failed: %s\nSQL: %s"
	MSG_MODEL_NOT_FOUND          = "Model not found (%s)"
	MSG_MODEL_REQUIRED           = "Model is required"
	MSG_FIELD_NOT_FOUND          = "Field not found (%s)"
	MSG_QUERY_EMPTY              = "Query is empty"
	MSG_QUERY_FROM_REQUIRED      = "Query 'from' is required"
	MSG_SYSTEMKEYFIELD_NOT_FOUND = "SystemKeyField not found"
	MSG_PRIMARYKEY_NOT_FOUND     = "PrimaryKey not found"
	MSG_NOT_DATA                 = "No data to %s %s model"
	MSG_NOT_INSERT_DATA          = "No insert data"
	MSG_MANY_INSERT_DATA         = "Many upsert data, only one is allowed"
	MSG_NOT_UPDATE_DATA          = "No update data"
	MSG_NOT_DELETE_DATA          = "No delete data"
	MSG_KEY_NOT_FOUND            = "Key not found"
	MSG_HISTORY_NOT_DEFINED      = "History not defined"
	MSG_HISTORY_NOT_FOUND        = "History not found"
	MSG_UNDO_NOT_DEFINED         = "Undo record not defined"
	MSG_UNDO_KEY_NOT_DEFINED     = "Undo key not defined"
	MSG_COMMAND_NOT_FOUND        = "Command not found"
	MSG_NOT_COMMAND              = "No command"
	MSG_SYSID_REQUIRED           = "Sysid is required"
	MSG_SCHEMA_NOT_USING_CORE    = "Schema is not using core"
	MSG_DATABASE_NOT_USING_CORE  = "Database is not using core"
	MSG_MODEL_NOT_USING_CORE     = "Model is not using core"
	MSG_ATTRIBUTE_REQUIRED       = "Attribute required (%s)"
	MSG_FIELD_REQUIRED           = "Field required (%s) model:%s"
	MSG_PRIMARY_KEY_REQUIRED     = "Primary key required (%s) model:%s"
	MSG_RECORD_NOT_FOUND         = "Record not found"
	MSG_INVALID_MODEL_PARAM      = "Invalid model params"
	MSG_ROLLBACK_ERROR           = "Rollback error: (%s)"
	MSG_COMMIT_ERROR             = "Commit error: (%s)"
	MSG_DATABASE_NOT_CONNECTED   = "Database not connected"
	MSG_EVENT_NOT_FOUND          = "Event not found (%s) in model %s"
	MSG_DATABASE_NOT_CONCURRENT  = "Database not concurrent"
)
